version: "3.8"

services:
  frps:
    images: frps:local
    restart: always
    ports:
      - '7000:7000'
      - '7500:7500'
      - '7001:7001'
      - '7080:80'
      - '7443:443'
      - '15000-15010:15000-15010'
    volumes:
      - '/var/frp/conf:/var/frp/conf'
